import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fffef6',
  '--slot4-page-text': '#10120f',
  '--slot4-panel-bg': '#f5f2e7',
  '--slot4-surface-bg': '#fffdf2',
  '--slot4-muted-text': '#666666',
  '--slot4-soft-muted-text': '#858575',
  '--slot4-accent': '#585e48',
  '--slot4-accent-fill': '#585e48',
  '--slot4-accent-soft': '#e6e6dc',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#2b332e',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e6e6dc',
  '--slot4-cream': '#fffef6',
  '--slot4-warm': '#f5f2e7',
  '--slot4-lavender': '#f0efe3',
  '--slot4-gray': '#e6e6dc',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#fffef6',
  '--editable-page-text': '#10120f',
  '--editable-container': '1320px',
  '--editable-border': '#d5d5d5',
  '--editable-nav-bg': '#fffef6',
  '--editable-nav-text': '#10120f',
  '--editable-nav-active': '#585e48',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#585e48',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#fffdf2',
  '--editable-footer-bg': '#2b332e',
  '--editable-footer-text': '#ffffff',
  '--editable-radius': '8px',
  '--editable-section-y': 'clamp(72px, 8vw, 120px)',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
    shadow: 'shadow-[0_10px_35px_rgba(43,51,46,0.06)]',
    shadowStrong: 'shadow-[0_30px_80px_rgba(43,51,46,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-[var(--editable-section-y)]',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-medium uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-5xl font-medium leading-[1.08] sm:text-6xl lg:text-[5.625rem]',
    sectionTitle: 'editable-display text-4xl font-medium leading-[1.15] sm:text-5xl lg:text-[3.625rem]',
    body: 'text-base leading-[1.625]',
  },
  surface: {
    card: `rounded-[var(--editable-radius)] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[var(--editable-radius)] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[var(--editable-radius)] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:opacity-95 active:scale-[0.99]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:-translate-y-0.5 hover:border-[var(--slot4-accent)] active:scale-[0.99]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-7 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:opacity-95 active:scale-[0.99]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[var(--editable-radius)] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-500 hover:-translate-y-1 hover:shadow-[0_28px_70px_rgba(43,51,46,0.14)]',
    fade: 'transition duration-500 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
